# KO_DOCKER_REPO should be either honeycombio (our dockerhub user), kind.local
# (for KinD) or ko.local
builds:
  - id: honeycomb-kubernetes-agent
    main: .
    ldflags:
      - -X honeycomb-kubernetes-agent/version.VERSION={{.Env.VERSION}}
