apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-hny-v1.1
  namespace: kube-system
  labels:
    k8s-app: fluentd-hny
    kubernetes.io/cluster-service: "true"
    version: v1.1
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-hny
        kubernetes.io/cluster-service: "true"
        version: v1.1
    spec:
      containers:
      - name: fluentd-hny
        image: myfluentd
        command:
          - '/bin/sh'
          - '-c'
          - '/usr/sbin/td-agent 2>&1 >> /var/log/fluentd.log'
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        env:
        - name: HONEYCOMB_WRITEKEY
          value: YOUR_WRITEKEY_HERE
        - name: HONEYCOMB_DATASET
          value: YOUR_DATASET_HERE
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

