# Service account for the agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: honeycomb-serviceaccount
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: honeycomb-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: honeycomb-serviceaccount
subjects:
- kind: ServiceAccount
  name: honeycomb-serviceaccount
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: honeycomb-serviceaccount
  namespace: kube-system
rules:
  - apiGroups:
    - "*"
    resources:
    - pods
    verbs:
    - list
    - watch

# ConfigMap specifying which logs the agent should watch
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: honeycomb-agent-config
  namespace: kube-system
data:
  config.yaml: |-
    apiHost: "http://apihost-service.default:5000"
    watchers:
      - dataset: kubernetestest
        labelSelector: app=nginx
        parser: nginx
    verbosity: debug

# Daemonset
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: honeycomb-agent
    kubernetes.io/cluster-service: 'true'
    version: v1.1
  name: honeycomb-agent-v1.1
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: honeycomb-agent
  template:
    metadata:
      labels:
        k8s-app: honeycomb-agent
        kubernetes.io/cluster-service: 'true'
        version: v1.1
    spec:
      containers:
      - env:
        - name: HONEYCOMB_WRITEKEY
          valueFrom:
            secretKeyRef:
              key: key
              name: honeycomb-writekey
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: honeycombio/honeycomb-kubernetes-agent:test
        imagePullPolicy: IfNotPresent
        name: honeycomb-agent
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: "/etc/honeycomb"
          name: config
          readOnly: false
        - mountPath: "/var/log"
          name: varlog
          readOnly: false
        - mountPath: "/var/lib/docker/containers"
          name: varlibdockercontainers
          readOnly: true
        - mountPath: "/mnt/sda1/var/lib/docker/containers"
          name: minikube
          readOnly: true
      serviceAccountName: honeycomb-serviceaccount
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          items:
          - key: config.yaml
            path: config.yaml
          name: honeycomb-agent-config
        name: config
      - hostPath:
          path: "/var/log"
        name: varlog
      - hostPath:
          path: "/var/lib/docker/containers"
        name: varlibdockercontainers
      - hostPath:
          path: "/mnt/sda1/var/lib/docker/containers"
        name: minikube
# Sample nginx deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# API host service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apihost-deployment
  namespace: default
  labels:
    app: apihost
spec:
  selector:
    matchLabels:
      app: apihost
  replicas: 1
  template:
    metadata:
      labels:
        app: apihost
    spec:
      containers:
      - name: apihost
        image: apihost:test
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: apihost-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: apihost
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
