package metrics

const (
	LabelNodeName      = PrefixNode + "name"
	LabelNamespaceName = PrefixNamespace + "name"
	LabelPodUid        = PrefixPod + "uid"
	LabelPodName       = PrefixPod + "name"
	LabelContainerName = PrefixContainer + "name"
	LabelContainerId   = PrefixContainer + "id"
	LabelVolumeName    = PrefixVolume + "name"

	StatusMessage      = PrefixStatus + "message"
	StatusReason       = PrefixStatus + "reason"
	StatusReady        = PrefixStatus + "ready"
	StatusState        = PrefixStatus + "state"
	StatusExitCode     = PrefixStatus + "exitcode"
	StatusPhase        = PrefixStatus + "phase"
	StatusRestart      = PrefixStatus + "restart"
	StatusRestartCount = PrefixStatus + "restart_count"
	StatusRestartDelta = PrefixStatus + "restart_delta"

	MeasureUptime                = "uptime"
	MeasureCpuUsage              = "cpu.usage"
	MeasureCpuUtilization        = "cpu.utilization"
	MeasureMemoryAvailable       = "memory.available"
	MeasureMemoryUsage           = "memory.usage"
	MeasureMemoryUtilization     = "memory.utilization"
	MeasureMemoryRSS             = "memory.rss"
	MeasureMemoryWorkingSet      = "memory.working_set"
	MeasureMemoryPageFaults      = "memory.page_faults"
	MeasureMemoryMajorPageFaults = "memory.major_page_faults"
	MeasureFilesystemAvailable   = "filesystem.available"
	MeasureFilesystemCapacity    = "filesystem.capacity"
	MeasureFilesystemUsage       = "filesystem.usage"
	MeasureNetworkBytesReceive   = "network.bytes.receive"
	MeasureNetworkBytesSend      = "network.bytes.send"
	MeasureNetworkErrorsReceive  = "network.errors.receive"
	MeasureNetworkErrorsSend     = "network.errors.send"
	MeasureVolumeAvailable       = "volume.available"
	MeasureVolumeCapacity        = "volume.capacity"
	MeasureVolumeUsed            = "volume.used"
	MeasureVolumeInodesTotal     = "volume.inodes.total"
	MeasureVolumeInodesFree      = "volume.inodes.free"
	MeasureVolumeInodesUsed      = "volume.inodes.used"

	PrefixK8s       = "k8s."
	PrefixMetrics   = "metrics."
	PrefixStatus    = "status."
	PrefixLabel     = "label."
	PrefixCluster   = PrefixK8s + "cluster."
	PrefixNode      = PrefixK8s + "node."
	PrefixNodeInfo  = PrefixNode + "nodeinfo."
	PrefixNamespace = PrefixK8s + "namespace."
	PrefixPod       = PrefixK8s + "pod."
	PrefixContainer = PrefixK8s + "container."
	PrefixVolume    = PrefixK8s + "volume."

	MetricSourceName       = "source"
	MetricSourceType       = "source.type"
	KubernetesResourceType = PrefixK8s + "resource.type"
)
